name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.4.4]
        rails-version:
          - 72
          - 80
        include:
          - ruby-version: 3.3.8
            rails-version: 70
          - ruby-version: 3.2.4
            rails-version: 71
          # TODO: once dependencies support it:
          # - ruby-version: 3.5.0-preview1
          #   rails-version: 80

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: delayed_job_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec
